version: "3.9"
services:
    # pirate_shopping:
    #     image: pirate_shopping
    #     build: .
    #     environment:
    #         - PORT=5000
    #         - HOST=0.0.0.0
    #         - ENV_NAME=prod
    #     ports:
    #         - "5000:5000"
    backend:
        image: online_shopping_backend
        build:
            context: .
            dockerfile: backend.Dockerfile
        volumes:
            - ./backend:/app/backend
            - /app/backend/node_modules
        environment:
            - PORT=5000
            - HOST=0.0.0.0
            - ENV_NAME=dev
        ports:
            - "5000:5000"
    react-app:
        image: online_shopping_react
        build:
            context: .
            dockerfile: react.Dockerfile
        volumes:
            - ./react-app:/app/react-app
            - /app/react-app/node_modules
        environment:
            - PORT=8080
            - VITE_BACKEND_URL=http://localhost:5000
            - VITE_ENV_NAME=dev
        ports:
            - "8080:8080"
