version: "3.9"
services:
    pirate_shopping:
        image: pirate_shopping
        build: .
        environment:
            - PORT=5000
            - HOST=0.0.0.0
            - NODE_ENV=production
        ports:
            - "5000:5000"
